name: "\U0001F41B Bug Report"
description: Submit a bug report to help us improve Monoid. To report a security related issue, please email us directly at security@monoid.so.
labels: ["02 Bug Report"]
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to file a bug report. Before creating a new
        issue, please make sure to take a few moments to check the issue tracker
        for existing issues about the bug.

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please share your system info with us so we can better understand the context of the bug.
      placeholder: |
        - Frontend vs Backend [e.g. Frontend]
        - Monoid Version / SHA7 [e.g. 1.0.0 / abc1234 ]
        - Language Version [e.g. Python 3.8]
        - Browser [e.g. Chrome]
        - OS: [e.g. MacOS]
    validations:
      required: true


  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      description: |
        Please provide a [code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem you ran into.
        If you have code snippets, error messages, stack traces please provide them here as well.
        Important! Use code tags to correctly format your code. See https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting

      placeholder: |
        Steps to reproduce the behavior:

          1.
          2.
          3.


  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you would expect to happen."